### ISSUE TITLE
Stack: separate export 3d tilesets from import data

### ISSUE THREAD

**Issue by yjytt59** [cambridge-cares/TheWorldAvatar#1045]
Currently, importing data to postgresql, extracting footprint and height, and exporting 3d tilesets all are running in one step. When I work on large datasets (SG data), it can't get tileset.json on my local computer. When I run this process in Digital Ocean, I get an error in the data upload container before exporting footprint and height. After increasing RAM of Digital Ocean to 64GB, Stack can get footprint and height, but got the same error and crashed before exporting 3d tilesets. In fact, the memory usage of Digital Ocean is less than 20%.

So firstly, I am not sure why Stack got the error when the usage of memory is not out of max. 
Second, is it better to separate the export operation to avoid the crash?
![image_2023_12_12T06_02_27_063Z](https://github.com/cambridge-cares/TheWorldAvatar/assets/15190590/fcec2fae-f371-4e41-9137-4aafd684fdba)
![image_2023_12_07T08_07_57_375Z](https://github.com/cambridge-cares/TheWorldAvatar/assets/15190590/df71d93c-e5ac-415a-9a4e-42ed7d52701c)

**Comment by ChungTingLao** [comment]
This error message suggests that the error happens during the upload of the building data (CityDB.java:104). This would have happened before any footprint or height augmentation. Can you share the error message that corresponds to the case where footprint and height have been calculated?

**Comment by yjytt59** [comment]
> This error message suggests that the error happens during the upload of the building data (CityDB.java:104). This would have happened before any footprint or height augmentation. Can you share the error message that corresponds to the case where footprint and height have been calculated?

I can't find any other info about this error in digital ocean. As I mentioned before, after increased RAM, it can get all footprint and height, but crashed again before extracting 3d tilesets with the same error. So I don't think this error is only related to footprint or height calculation.
