### ISSUE TITLE
DVTF: can not visualise city furniture in 2D and 3D

### ISSUE THREAD

**Issue by yjytt59** [cambridge-cares/TheWorldAvatar#1066]
1. Mapbox: city furniture store in city_furniture in lod1 (lod1_brep_id), which has not height and footprint. So it can not be compatible with current mapbox visualisation using 2d polygon and extruding by height. Maybe need a solution to change a bit of stack footprint generation and mapbox visualisation.
2. Cesium: 3d tilesets don't query city furniture and export to visualization.

**Comment by ChungTingLao** [comment]
Resolved. SQL script can be found in https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Deploy/stacks/Singapore/custom_sql_scripts/cityfurniture-footprint-height.sql
