### ISSUE TITLE
TWA-VF UI bugs

### ISSUE THREAD

**Issue by qhouyee** [cambridge-cares/TheWorldAvatar#1077]
Found some bugs with the user interface of TWA-VF version 4.5.0:

1) The tool-tip for the expand button on the top right is hidden. Adding a `z-index` in css will quickly fix this in the `tooltip` class
![image](https://github.com/cambridge-cares/TheWorldAvatar/assets/89125222/34954f5c-b910-44b0-9644-896900fafd88)

2) Text in the expanded version cannot be scrolled or viewed at certain resolutions. 
![image](https://github.com/cambridge-cares/TheWorldAvatar/assets/89125222/e84bac72-4a0e-4573-9dc6-7329dfa96520)

3) Text content in the side panel is cut away by the wave container
![image](https://github.com/cambridge-cares/TheWorldAvatar/assets/89125222/8f104229-cf1a-4d43-9cdf-15e0c1725528)

4) The World Avatar label in the bottom-center of the side panel disappears whenever clicking the return button after selecting any item. Seems to be something going on with the use of # in the url with the return button

**Comment by jlai2021** [comment]
@qhouyee any update on this issue?

**Comment by Ushcode** [comment]
Issues fixed in various merges in recent months
