### ISSUE TITLE
py4jps wrapper allows multiple JVMs to be initialised

### ISSUE THREAD

**Issue by gpeb2** [cambridge-cares/TheWorldAvatar#1230]
Each call to ```jpsBaseLibGW.launchGateway``` starts a new Java Virtual Machine (JVM) and if you create a Java object in one and then try to pass it to the other then bad things will probably happen.
The solution is to make this function create a singleton object that is initialised once and then just returned on subsequent calls.

**Comment by jb2197** [comment]
As discussed, the issue is because a new Java gateway object is created when calling `JpsBaseLib()` which makes Java objects in different JVMs get passed across.
