### ISSUE TITLE
Use pnpm in twa-vf

### ISSUE THREAD

**Issue by Ushcode** [cambridge-cares/TheWorldAvatar#1247]
`pnpm` has shown significant performance advantages over node's built in `npm` and seems like the better choice for js package management.

It is included in corepack and just needs to be migrated.

There is a `pnpm import` command that converts a `packages-lock.json` to a `pnpm-lock.yaml`

[migration guide](https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04)

**Comment by qhouyee** [comment]
Closed in #1301
