### ISSUE TITLE
DTVF: Refactoring

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#145]
A large number of changes have been made to the DTVF during an extremely time-sensitive project. This means that additions have been made without considering their wider effect. To resolve this build up before it becomes unmaintainable, I propose to change the following:

- Add a Source class to represent an individual data source
- Add a Layer class to represent an individual, configurable visual layer
- Add a DataGroup class (that supports nesting) to represent each group of Sources
- Provide more (and better documented) places to inject custom, implementation specific, callbacks
- Add unit tests

**Comment by mdhillmancmcl** [comment]
The first three steps mentioned above have now been implemented.

**Comment by mdhillman** [comment]
As the majority of this issue is completed, I am going to mark it closed and split out the "Add unit tests" desire to a new issue where it can be better documented and updated.
