### ISSUE TITLE
DTVF: Optimisation

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#161]
If we continue to aim to combine our existing visualisations into a single, layered one, the DTVF will need work to better handle large amounts of data.

Possibilities that need to be explored:
- Lazy Loading
- Minifiying data sources
- Server side (multi-threaded) data loading

**Comment by qhouyee** [comment]
These issues have been resolved in the latest iteration of the visualisation framework which was merged with #1085
