### ISSUE TITLE
Derivation Framework: Concurrent HTTP request handling

### ISSUE THREAD

**Issue by jb2197** [cambridge-cares/TheWorldAvatar#184]
# Issue
During testing the mixed type of derivation DAGs (case 5 in DerivationAsynExample), an issue was found due to the way how tomcat handles the concurrent HTTP requests. In the derivation DAG, two `OntoDerivation:Requested` asynchronous derivations (MaxValueDerivation and MinValueDerivation) depend on the same synchronous derivation (RNGDerivation). As the derivation agents (MaxValue Agent and MinValue Agent) were initialised with the same periodical timescale for monitoring derivations, they fire the HTTP request for an update of RNGDerivation at the same time. Upon receiving the concurrent HTTP requests, RNG Agent handles them with different threads (i.e. http-nio-8080-exec-4 and http-nio-8080-exec-5 in the log file), therefore, the RNG Agent computes the derivation outputs with the same inputs twice and return the response **respectively** to MaxValue Agent and MinValue Agent. The two sets of outputs were then **both** written to the knowledge graph by the derivation client that ran by MaxValue/MinValue Agent, yielding multiple outputs `OntoDerivation:belongsTo` RNG Derivation, also MaxValue/MinValue Derivation both `OntoDerivation:isDerivedFrom` multiple inputs - as shown in below screenshot. Both MaxValue/MinValue Agent were coded that they assume there's only one IRI passed in so it operates on the first IRI in the list, although the derivation inputs retrieved by both agents will have two instances. The rest of the computation and the function of Difference Agent are thus still able to complete execution without errors (although the results are inconsistent with the multiple outputs/inputs derivation markup). The test case of case 5 (testMaxMinDiffAsync(), current commented out) in DockerIntegrationTest.java fails as it checks if the outputs generated by RNG Derivation contain the correct amount of points - which is expecting 7 instead of the actual 14 due to multiple calculations.

RNG Derivation marked with multiple outputs: 
![rng_derivation_multiple_outputs](https://user-images.githubusercontent.com/49490446/164014230-4997502b-9458-4406-b3ae-bf58ddefb48b.PNG)

MaxValue Derivation marked with multiple inputs: 
![max_derivation_multiple_inputs](https://user-images.githubusercontent.com/49490446/164014883-06d2b20a-1cf9-47c0-8505-336f38d1cbb9.PNG)

MinValue Derivation marked with multiple inputs: 
![min_derivation_multiple_inputs](https://user-images.githubusercontent.com/49490446/164014853-3ed89df0-dc0c-4be1-80df-76e7ee674b23.PNG)

Concise version (logs on jdbc removed, start from InputAgent invoked): [case5_error_concise_record.log](https://github.com/cambridge-cares/TheWorldAvatar/files/8512822/case5_error_concise_record.log)

Full log on the issue: [case5_error_full_record.log](https://github.com/cambridge-cares/TheWorldAvatar/files/8512807/case5_error_full_record.log)

Full sets of triples (ttl format): [case5_error_all_triples.txt](https://github.com/cambridge-cares/TheWorldAvatar/files/8513317/case5_error_all_triples.txt)

# Naive work-around
A naively work-around (for the short term) is to initialise the agent with different frequencies of monitoring the derivations or different initial delays so that different agents are less likely to request updates of the same resources at the same time. However, we need a better approach to address this properly in the long run.

In the below logs, you may see that RNG Agent was only requested via HTTP request once, instead of twice in the above situation. The update was thus all done as normal and no error occurred for testMaxMinDiffAsync().

RNG Derivation marked with one output as expected: 
![rng_derivation_one_output](https://user-images.githubusercontent.com/49490446/164027617-c699477f-5d89-4c38-8355-e51024c90f2f.PNG)

Concise version (logs on jdbc removed, start from InputAgent invoked): [case5_work_around_concise_record.log](https://github.com/cambridge-cares/TheWorldAvatar/files/8513822/case5_work_around_concise_record.log)

Full log for the same DAG case 5 if the periodical timescales are initialised differently: [case5_work_around_full_record.log](https://github.com/cambridge-cares/TheWorldAvatar/files/8513826/case5_work_around_full_record.log)

Full sets of tripels (ttl format): [case5_work_around_all_triples.txt](https://github.com/cambridge-cares/TheWorldAvatar/files/8513850/case5_work_around_all_triples.txt)

**Comment by kokfoongcmcl** [comment]
Sounds like you traversed to the same edge twice in your update code, isn't it straightforward to make it such that it does not do so by checking the value returned by addEdge?

**Comment by jb2197** [comment]
> Sounds like you traversed to the same edge twice in your update code, isn't it straightforward to make it such that it does not do so by checking the value returned by addEdge?

The issue was caused by multiple agents requesting updates of the same upstream derivation via HTTP request at the same time, i.e. multiple asynchronous derivations `OntoDerivation:isDerivedFrom/OntoDerivation:belongsTo` the same synchronous derivation. For the specific case aforementioned, please see https://raw.githubusercontent.com/cambridge-cares/TheWorldAvatar/154-dev-unified-derivation-framework/Agents/DerivationAsynExample/DerivationAsynExampleMode2.svg and imagine the RNG Derivation is created as an instance of `OntoDerivation:Derivation` but all other derivations as instances of `OntoDerivation:DerivationAsyn`. 

Re preventing traversing the same edge twice, I have provided a solution like https://github.com/cambridge-cares/TheWorldAvatar/blob/154-dev-unified-derivation-framework/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationClient.java#L946, more detailed explanation can be found at https://github.com/cambridge-cares/TheWorldAvatar/blob/154-dev-unified-derivation-framework/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationClient.java#L893, you may compare it with the original version at https://github.com/cambridge-cares/TheWorldAvatar/blob/fbb895e8233b397e26f7e622111207985b7ba08d/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationClient.java#L1085. Please check if you agree.

**Comment by jb2197** [comment]
The naive work-around is provided in commit https://github.com/cambridge-cares/TheWorldAvatar/commit/ac86b489d5a42cacfbf5ca751274d144034579f1. One may refer to https://github.com/cambridge-cares/TheWorldAvatar/pull/185 for more context.

**Comment by kokfoongcmcl** [comment]
If I understood this correctly, this is fired by the updatePureSyncDerivations in monitorDerivation?

I believe what you should do is to write the SPARQL updates with a sub query (Example 6 https://www.w3.org/TR/sparql11-update/), I *think* the triple-store processes each query one after another, so if the first query is already executed, the state of the KG will be different, and the second query should have no effect.

**Comment by jb2197** [comment]
> If I understood this correctly, this is fired by the updatePureSyncDerivations in monitorDerivation?

Yes, that's correct, the HTTP requests are fired by the DerivationAgent when updating the inputs (that themselves `belongsTo` synchronous derivations) to the asynchronous derivation that it is monitoring. 

> I believe what you should do is to write the SPARQL updates with a sub query (Example 6 https://www.w3.org/TR/sparql11-update/), I _think_ the triple-store processes each query one after another, so if the first query is already executed, the state of the KG will be different, and the second query should have no effect.

I think this might work, we can make the SPARQL updates only execute if the derivation is still outdated. I suppose the only consequence is doubling the work when computing outputs within processRequestParameter (or x-times depending on how many concurrent HTTP requests). I will have a try.

**Comment by jb2197** [comment]
As discussed, the combined SPARQL update provided in the fix should also include triples about the newly created instances to properly address the concurrent HTTP request issue, besides all triples related to `OntoDerivation:isDerivedFrom` and `OntoDerivation:belongsTo`, triples related to the status, and triples related to the timestamp. 

This might be doable if we set the function processRequestParameters(DerivationInputs) to return the instance of the class instead of only IRIs, and let the DerivationAgent perform the SPARQL update. However, there seems no easy way to do it now.

**Comment by kokfoongcmcl** [comment]
It might not be even possible with the current SPARQL update standard as you need to bind the variables in the query to the insert/delete triples. It might be possible if we write the agents to just modify the triples containing the values instead of writing a brand new instance

**Comment by jb2197** [comment]
> It might not be even possible with the current SPARQL update standard as you need to bind the variables in the query to the insert/delete triples. It might be possible if we write the agents to just modify the triples containing the values instead of writing a brand new instance

As discussed, the `delete`/`insert` clauses will only be executed if there are patterns matching the `where` clause, even if the triples in the `delete`/`insert` are not bound with the variables in the `where` clause.

To address the issue when updating normal `OntoDerivation:Derivation`, commits were provided in https://github.com/cambridge-cares/TheWorldAvatar/pull/185 that execute the SPARQL update with sub query at DerivationAgent side when writing all the new derived triples back to the knowledge graph. The SPARQL update is implemented in a way that it will only be executed if the target derivation is still outdated. The subsequent SPARQL update in the concurrent HTTP requests will thus not be executed, which prevents the duplicated entries in the knowledge graph.

For agents updating `OntoDerivation:DerivationWithTimeSeries`, the derived instances are stored as time series data in the database. As the TimeSeriesClient overwrites the entry with the same timestamp by default, the concurrent HTTP requests will not result in duplicated entries in the knowledge graph (database in this case).

Based on these behaviours, this issue is thus believed to be (largely) resolved.
