### ISSUE TITLE
Stack NGINX setting seem inappropriate and need to be updated

### ISSUE THREAD

**Issue by markushofmeister** [cambridge-cares/TheWorldAvatar#330]
I observed that the Ontop client might face issues when evaluating larger SPARQL queries. I am using a query of the following form to retrieve the geolocation of a list of station iris of interest `{iris}`. This query works perfectly for list sizes up to approx 500 stations, but fails for sizes exceeding them. The workaround is to query in batches, but a limit of 500 seems quite restrictive.

`SELECT ?station ?wkt
 WHERE {
      FILTER (?station IN ({iris}) ) 
      ?station <{RDF_TYPE}> <{GEO_FEATURE}> ;
                   <{GEO_HAS_GEOMETRY}>/<{GEO_ASWKT}> ?wkt 
       }`

**Comment by kokfoongcmcl** [comment]
![image](https://user-images.githubusercontent.com/71323448/189632345-e51d7d5f-c227-47f8-83e5-6427896296c4.png)
I'm able to do large queries, maybe you can show me your dataset

**Comment by markushofmeister** [comment]
Then the potential issue might be the large number of IRIs in the `FILTER IN` clause (e.g. approx. 6000 IRIs). The same query pattern runs without issues on Blazegraph but not via Ontop, where it returns a `NullPointer`. If the number of IRIs in the filter clause is reduced (i.e. << 500), the query runs successfully
![image](https://user-images.githubusercontent.com/79832739/189635386-b85e7a52-c4e5-410d-900f-16458168ea33.png)
![image](https://user-images.githubusercontent.com/79832739/189635442-16337532-1e68-4526-8cee-7800ebd21d91.png)

**Comment by kokfoongcmcl** [comment]
have you tried the "VALUES" syntax?

**Comment by markushofmeister** [comment]
> have you tried the "VALUES" syntax?

Do we have experience/evidence that this will be quicker or more economical? Otherwise, I still believe that there might be heap space or other issues with ontop as the successful query execution clearly depends on the filter size

**Comment by kokfoongcmcl** [comment]
I'm not sure, it depends how ontop translates that into the SQL query

**Comment by markushofmeister** [comment]
![image](https://user-images.githubusercontent.com/79832739/189644339-36bfb23a-11f2-4349-b909-5c956a71a654.png)
Rephrasing the query to use `VALUES` instead of the `IN` filter now causes a different issue. The equivalent query in Blazegraph runs in approx. 2 sec.
I will go ahead with querying in chunks, but it might be worth keeping this in mind for the future.

**Comment by kokfoongcmcl** [comment]
> The equivalent query in Blazegraph runs in approx. 2 sec.

do you mean you run this on a separate dataset or did you use the service command?

**Comment by markushofmeister** [comment]
> > The equivalent query in Blazegraph runs in approx. 2 sec.
> 
> do you mean you run this on a separate dataset or did you use the service command?

Different dataset, but 1) exactly same `FILTER IN` or `VALUES` expression, respectively, and 2) same query pattern, i.e. one single relationship and one relationship path expression

**Comment by kokfoongcmcl** [comment]
I'm also seeing this issue on a separate application, I think this can be solved by tweaking the nginx settings

**Comment by markushofmeister** [comment]
@gpeb2 Did you have time to look into this already?
We know also observe issues with running the Building Matching Agent on the instantiated Building EPC data due to error code "413 Request Entity Too Large". The very same agent requests work nicely on local endpoint or remote endpoints hosted on Digital Ocean outside the stack
