### ISSUE TITLE
Make it possible to upload icon files to GeoServer 

### ISSUE THREAD

**Issue by gpeb2** [cambridge-cares/TheWorldAvatar#384]
Many styles that we want to use with GeoServer require separate image files for their icons.
Whilst the GeoServer REST API supports this it is limited to only one type of style file,

>  [You can also use PUT with a ZIP file to upload a SLD 1.0 (application/vnd.ogc.sld+xml) file and any associated icon files](https://docs.geoserver.org/latest/en/api/#1.0.0/styles.yaml).

Also the Java library that is currently being used to make the GeoServer REST API calls does not support this. A simple class that extends the existing one could be written to add this functionality though.

The alternative option is to just add a separate step that copies the images into the correct directory in the GeoServer container.

**Comment by mdhillmancmcl** [comment]
**Side note:** when client-side styling is supported (i.e. in Mapbox), the DTVF currently requires icons to be loaded as separate files. Icons are loaded from URLs, so if this can be achieved in a way that Geoserver can host these icons and make them accessible, then it can be used for client-side styling as well as server-side.
