### ISSUE TITLE
DTVF: Functionality to rotate 3D Cesium tilesets

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#426]
In the Cesium version of the DTVF, the "position" node in a tiles source in data.json would need two additional numbers (appended to the x, y, and z coordinates): a rotation angle about the x-axis, and a rotation angle about the z-axis (in an assumed unit, e.g. deg or rad).

Example JS code to implement the rotation can be found [here](https://github.com/cambridge-cares/TheWorldAvatar/blob/dev-bim-cesium-visualisation/BIMCesiumVisualisation/src/js/functions/cesium_data_handler.js).

**Comment by mdhillman** [comment]
This has now been added as part of PR #414. Details have been added to the README for Cesium visualisations, but are also copied here for convenience.

- For `tiles` sources, optional `position` and `rotation` fields can also be set.
  - The `position` field is a three value array of the form `[longitude, latitude, height]`.
  - The `rotation` field requires the `position` field to be present, and is a three value array of the form `[roll, pitch, heading]`. Cesium defines Roll as the rotation about the positive X axis, Pitch as the rotation about the negative Y axis, and Heading as the rotation about the negative Z axis
