### ISSUE TITLE
DTVF: Cesium 3D tiles clipping plane feature

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#491]
We now have highly detailed building representations that include numerous internal features such as furniture and sensors that we want to be able to click on and view metadata etc. In order to be able to see such features inside buildings, the clipping plane feature provided by Cesium is exceedingly useful. This would need to be added to the DTVF, with suitable UI controls.
![Clipping-JS-implementation-2](https://user-images.githubusercontent.com/46816676/204888751-86f75041-100f-4ede-8d63-f5586a2e7a57.png)

**Comment by mdhillman** [comment]
I am in the process of looking into this, this functionality (along with the ability to handle multiple tilesets, and mouse controls to move the plane), is actually quite complicated and make take me a day or so to figure out.

**Comment by mdhillman** [comment]
I have spent a full day on this now and am unable to get this to function correctly using house 45 as an example. Within the framework I am unable to get the clipping functionality to work at all, and within a standalone example (see below), the clipping is still incorrect.

This may have something to do with the tileset itself, as when displaying the bounding volumes, it appears that house may be outside it's own bounding space. I've set up a Cesium Sandcastle example [here](https://tinyurl.com/yspj7rms) to demonstrate the issue.

As such, this request will have to go on the back-burner until more development time is available.

**Comment by sm453** [comment]
> I have spent a full day on this now and am unable to get this to function correctly using house 45 as an example. Within the framework I am unable to get the clipping functionality to work at all, and within a standalone example (see below), the clipping is still incorrect.
> 
> This may have something to do with the tileset itself, as when displaying the bounding volumes, it appears that house may be outside it's own bounding space. I've set up a Cesium Sandcastle example [here](https://tinyurl.com/yspj7rms) to demonstrate the issue.
> 
> As such, this request will have to go on the back-burner until more development time is available.

You may want to have a chat with @qhouyee, who has been able to use this feature at least to an extent that it does a good-enough job. Also, as we have control over the tileset source, if we understand the issue with the bounding space, then I assume we can fix it.

**Comment by mdhillman** [comment]
With @qhouyee's help I've been able to get this functional. I am now cleaning it up, ensuring the relevant UI controls are present, and making sure each tileset can (optionally) have a clipping plane with no interference between them.
