### ISSUE TITLE
The maven build of JPS_BASE_LIB fails

### ISSUE THREAD

**Issue by Shiying99** [cambridge-cares/TheWorldAvatar#51]
Hi. I tried to build the package JPS_BASE_LIB (develop branch) on my windows machine recently. 

It raises the following error:  
[ERROR]     Non-resolvable parent POM for uk.ac.cam.cares.jps:jps-base-lib:1.4.0-SNAPSHOT: Could not find artifact uk.ac.cam.cares.jps:jps-parent-pom:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 22, column 13 -> [Help 2]

I have been successfully built the package sometime before. So I assume the recent update breaks the build.  
Please help. Thank you

**Comment by gpeb2** [comment]
The instructions on how to set your machine up to pull from the "cambridge-cares" Maven repository hosted on GitHub are written in the Wiki here, https://github.com/cambridge-cares/TheWorldAvatar/wiki/Packages.
Please follow those instruction and then update this issue as appropriate (either close it if it is solved or add a new comment if it makes no difference).

**Comment by gpeb2** [comment]
I assume this is no longer an issue.
