### ISSUE TITLE
Feature Info Agent: Each time series query should have its own RDB

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#518]
> > > For time series queries, would it be possible to make each of the `queries` have its own `database_name` parameter (in the config json)? In a complex use case it may not be practical to have all time series in the same database, hence a single, global setting is a bit restrictive.
> > 
> > Or even better, read the hasRDB property from the KG, but whatever is quicker to implement wins for now...
> 
> just have to be careful, the URL is probably the one accessed by the agent instantiating the time series, not the external one

Quickest solution is to update the config to allow the specification of a DB name per class. I can do this but it'll require some changes to the intenral data structures, so I'm not sure it'll happen before the demonstration. In which case, should it hold this PR up or be done as a feature afterwards?

I'm not sure if _all_ data has the `hasRDB` relationship yet, pretty sure the data on our development servers (which I use for testing) doesn't. Until that happens, I'd be wary of relying on it.

_Originally posted by @mdhillman in https://github.com/cambridge-cares/TheWorldAvatar/issues/466#issuecomment-1340711519_

Or, in the super-fancy version, make the access agent work out which RDB to use...

**Comment by mdhillman** [comment]
Each registered class now contains its own parameter for the database name. Future updates, such as using the `hasRDB` relationship, or the access agent, are unlikely to happen in the near term, and will require other developers (so I'm closing _this_ issue as completed).

This has been updated as part of PR #466.
