### ISSUE TITLE
DTVF: Pop-up window handling

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#534]
Currently, the pop-up window when hovering over features is hard-coded to a fixed size. It would be great if this was customisable and/or auto-adjusted to the display string.

**Comment by mdhillman** [comment]
I've adjusted the CSS to fix this; long site names and long descriptions now display better.

![Updated popup](https://i.postimg.cc/j5JCLqs7/long-site-name.png)

**Comment by mdhillman** [comment]
The DTVF currently has two implementations for this popup system, one using the Mapbox provided classes, and a generic HTML/JS one for Cesium. This issue is being re-opened with the aim to unify these systems.

**Comment by mdhillman** [comment]
Progress on this has stalled as other features have taken priority. Note that this is still an active, albiet low priority, issue.

**Comment by mdhillman** [comment]
In progress on the `dev-twa-fix` branch, watch this space for a PR soon!
