### ISSUE TITLE
DTVF/FIA: Time series only - no metadata query.

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#535]
It would be great if the metadata query in the Feature Info Agent config json was optional, too, with the front-end displaying just the PostGIS metadata if no such query is provided. This would allow attaching time series to datasets that have metadata from PostGIS, without having to write an OBDA mapping and a metadata query that pulls out the metadata that would be displayed otherwise anyway.

_Originally posted by @sm453 in https://github.com/cambridge-cares/TheWorldAvatar/issues/466#issuecomment-1344121256_

**Comment by mdhillman** [comment]
This has been address in PR #466.
