### ISSUE TITLE
DTVF/FIA: Time series with different time-stamp sets associated to single feature

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#536]
Currently, if multiple time series are associated to a single feature (to be displayed on the side-panel, selectable through the dropdown combo box), they have to share a single array of time stamps. In response to a time series query, the Feature Info Agent returns arrays of the values of each of the requested quantities, but only a single array of time stamps. This implicit assumption that all time series associated to a feature share the same time stamp values is quite restrictive. The FIA should return one array of time stamps for each of the requested quantities (even if these time stamp values are repeated).

**Comment by mdhillman** [comment]
This has been address in PR #466.
