### ISSUE TITLE
Stack manager to cleanly remove agents

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#586]
Currently, adding agents to an already running stack is straightforward: Just copy a config json file into the `inputs/config` folder and start the stack manager. However, removing such agents with `docker rm -f` and removing the config json files leaves (then no longer valid) routing information in the stack nginx container. Any further agents that are subsequently added are not reachable (404). It appears nginx fails at the invalid entry and does not consider any following entries. The easiest work-around is to kill the stack altogether and start it again from scratch.

It would be nice if there was a way to cleanly remove a running agent from a running stack, so that users can dynamically add and remove containers as they see fit.

**Comment by markushofmeister** [comment]
Alternatively to killing and restarting the stack, the following commands run inside the `nginx` container also help to remove those outdated files which prevent new routing information to be added.

```bash
# Test NGINX configuration to determine potentially erroneous (upstream) configuration
nginx -t
# Delete potentially erroneous/outdated configuration files
rm /etc/nginx/conf.d/...
rm /etc/nginx/conf.d/locations/...
# Verify that NGINX configuration is corrected
nginx -t
# expected output: the configuration file /etc/nginx/nginx.conf syntax is ok
# expected output: configuration file /etc/nginx/nginx.conf test is successful

# Reload NGINX configuration
nginx -s reload  
# expected output: signal process started
```

This temporary solution has been "suggested" by @gpeb2, but I agree that a more robust and clean implementation would be highly appreciated.
