### ISSUE TITLE
DTVF: Unable to display time series chart and table at certain resolution

### ISSUE THREAD

**Issue by qhouyee** [cambridge-cares/TheWorldAvatar#658]
When displaying the time series chart at certain resolutions, the panel is unable to view the time series table as well. There is no current way to scroll down or interact with the panel to adjust the display. My current workaround is to adjust the browser's zoom level so that both are viewable.

![image](https://user-images.githubusercontent.com/89125222/224624958-702d840e-9ee1-4844-bf53-80b8315f7f5a.png)

**Comment by mdhillman** [comment]
Related to issue #415

**Comment by mdhillman** [comment]
See resolution of issue #415
