### ISSUE TITLE
Volume for custom stack containers are not linked to the host machine

### ISSUE THREAD

**Issue by qhouyee** [cambridge-cares/TheWorldAvatar#689]
I am in the midst of stackerising the below agent, and have the following stack-manager input config file:
  https://github.com/cambridge-cares/TheWorldAvatar/blob/dev-data-bridge-agent/Agents/DataBridgeAgent/docker/data-bridge-agent.json

Using the above config, the custom container is able to start and create the bind folder. However, this folder is not linked to the host machine, and is empty (which it should not be). I have tried the following:
1. Trying different variations of absolute and relative file paths
- I could spin up the custom container for relative file paths, but the folder remains empty
- For absolute file paths, I cannot start the custom container, which always comes with errors
    Windows  - C://User/.../TheWorldAvatar/Agents/DataBridgeAgent/config/
    WSL - /mnt/c/.../TheWorldAvatar/Agents/DataBridgeAgent/config/

2. Changing the mount type to "bind" and "volume" for all the above variations

**Comment by sm453** [comment]
Relative paths should not work, as this is not implemented (yet). Absolute paths are known to work, though, as we have used this successfully for several existing agents. What error message are you getting for an absolute path?

**Comment by qhouyee** [comment]
I managed to get it working using  `/mnt/c/Users/...` which is the absolute file path for its WSL equivalent.

When I input the following absolute path starting with C://, I received the following error. I tested for both `.../config` and `.../config/`

`Exception in thread "main" com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: C://Users/HQUE01/Documents/GitHub/TheWorldAvatar/Agents/DataBridgeAgent/config is not an absolute path`

When I tried the file path without the C://, the agent is started but the config folder is empty within the stack container. This is probably because it is a relative file path and wasn't properly mounted. I have tried several configuration with relative file path from the stack manager folder to the agent but that was not working either.

> /Users/HQUE01/Documents/GitHub/TheWorldAvatar/Agents/DataBridgeAgent/config

`[{"ID":"xuis4n2lrrzntzig04pr27isj","Version":"Index":1065},"CreatedAt":"2023-04-05T09:02:08.285941Z","UpdatedAt":"2023-04-05T09:02:08.498381Z","Labels":{},"Spec":{"ContainerSpec":{"Image":"data-bridge-agent:1.0.0","Labels": "com.docker.compose.project":"local","com.docker.stack.namespace":"local","desktop.docker.io/mounts/0/Source":"/Users/HQUE01/Documents/GitHub/TheWorldAvatar/Agents/DataBridgeAgent/config","desktop.docker.io/mounts/0/SourceKind":"wsl2DistroFile","desktop.docker.io/mounts/0/Target":"/usr/local/tomcat/config","desktop.docker.io/mounts/2/Source":"/var/run/docker.sock","desktop.docker.io/mounts/2/SourceKind":"dockerSocketWsl2","desktop.docker.io/mounts/2/Target":"/var/run/docker.sock"},"Hostname":"local-data-bridge-agent","Env":["STACK_NAME=local"],"Mounts":[{"Type":"bind","Source":"/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/332081990f7c09bc478d271b6a1487aa49b43e3037ab086e6dae92d5e2c53b4c","Target":"/usr/local/tomcat/config"},{"Type":"volume","Source":"local_scratch","Target":"/stack_scratch","VolumeOptions":{"Labels":{"com.docker.compose.project":"local","com.docker.stack.namespace":"local"}}},{"Type":"bind","Source":"/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/71329c4cc6e32171553fa81d044eb31d1a3aac52ba9376c4a99f4505c494cf5b","Target":"/var/run/docker.sock"}],"Secrets":[{"File":"Name":"postgis_password","UID":"0","GID":"0","Mode":292},"SecretID":"qvdykoz05fos3592qu9qp87cg","SecretName":"local_postgis_password"}],"Configs":[{"File":"Name":"blazegraph","UID":"0","GID":"0","Mode":292},"ConfigID":"bavsuxjb2r1zk5isy5u36949w","ConfigName":"local_blazegraph"},{"File":"Name":"postgis","UID":"0","GID":"0","Mode":292},"ConfigID":"vrmuo1bki0tw7z2kw3ex2mpxp","ConfigName":"local_postgis"}],"Isolation":"default"},"RestartPolicy":{"Condition":"none","MaxAttempts":0},"Networks":[{"Target":"xlr5f0e76g37rtebxds6euc4i"}],"ForceUpdate":0},"ServiceID":"oh90i9yynpvfysv5npo2rey93","Slot":1,"NodeID":"jgx6yd9gqx0o4b1tk9gigzxgs","Status":"Timestamp":"2023-04-05T09:02:08.4645746Z","State":"preparing","Message":"preparing","PortStatus":{}},"DesiredState":"running","NetworksAttachments":[{"Network":{"ID":"xlr5f0e76g37rtebxds6euc4i","Version":{"Index":961},"CreatedAt":"2023-04-05T08:58:41.5973971Z","UpdatedAt":"2023-04-05T08:58:41.611854Z","Spec":{"Name":"local","Labels":"com.docker.stack.namespace":"local"},"DriverConfiguration":"Name":"overlay"},"Attachable":true,"Scope":"swarm"},"DriverState":"Name":"overlay","Options":"com.docker.network.driver.overlay.vxlanid_list":"4100"}},"IPAMOptions":{"Driver":{"Name":"default"},"Configs":[{"Subnet":"10.0.4.0/24","Gateway":"10.0.4.1"}]}},"Addresses":["10.0.4.22/24"]}]}][\n]"`

**Comment by gpeb2** [comment]
Two comments:

1. Support for relative paths is being added in pull request #742.
2. On Windows machines Docker runs in WSL so any absolute paths must use the WSL form of the path starting with "/mnt/c/" and not the Windows "C:\" or Git bash "/c/" forms.
