### ISSUE TITLE
DTVF: Support for 'gml_id' in place of 'iri'

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#738]
Building data currently in use at CARES uses the `gml_id` parameter as a unique identifier rather than `iri`, and the `iri` field is not present in Postgres/PostGIS (and hence missing from the generated tileset files). However, @yjytt59 informs me that the buildings _do_ have an IRI within the knowledge graph, and it is based on the `gml_id`.

The FeatureInfoAgent (FIA) is currently designed to support look up via the IRI, and only the IRI; on the (perhaps out of date?) assumption that this was the unique ID that will be used across all data sets.

Rather than redesign the 3D building data handling to include the `iri`, or the FIA to support any parameter as the unique ID (both of wwhich _could_ be done, but it not suggested at this juncture), a half-way-house solution has been proposed:

- When an entity is selected in the map:
  - If an `iri` parameter is present, send to the FIA as usual
  - If `iri` is missing, but `gml_id` is present, build the IRI by prepending `https://theworldavatar.com/` then send this to the FIA as usual.
  
This will need to be tested, but the belief is that this would technically resolve the issue with minimal changes.

**Comment by mdhillman** [comment]
I'm adding in @sm453 and @gpeb2 here to keep them informed of coming changes. I would also like to confirm if we do want to support using _any_ parameter as the unique ID (which could be flexible), or if we should enforce the use of using the IRI (which would make generalising easier).

**Comment by sm453** [comment]
I feel there is a need for clarification here. The assumption that the IRI is the unique ID of an individual is most definitely _not_ out of date. Rather, it is one of the most fundamental principles of the KG (and the Semantic Web), and I see no reasons whatsoever for compromising this. In fact, using pseudo-replacements (like to one you mention for buildings, or others that are in use e.g. for chemical species) cause more problems than they solve. So, I strongly advise against this.

Having said that, when _generating_ IRIs (for new individuals), one is of course free to use whatever information is available, as long as one _never_ uses the IRI string to infer meaning or draw conclusions of any kind about the individual. The importance of this latter point cannot be overemphasised.

**Comment by mdhillman** [comment]
@sm453 would you then recommend that the 3D building data is updated so that the IRI of the building _is_ included as a column in the RDB (which would then be propagated into the generated tileset)?

**Comment by sm453** [comment]
> @sm453 would you then recommend that the 3D building data is updated so that the IRI of the building _is_ included as a column in the RDB (which would then be propagated into the generated tileset)?

I would much prefer this. At least it would be the lesser of evils in my view...

(Think of it that way, @mdhillman, if we extend the FIA to allow `gml_id`, you may soon find a queue of people going "Oh, @mdhillman, can you extend the FIA to allow `InChI` for my chemical species?" etc. etc.)

**Comment by mdhillman** [comment]
I will close this issue and open a new one.
