### ISSUE TITLE
Include IRI parameter in 3D building data.

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#739]
Please see issue #738 for background.

To support use in the visualisation framework, FeatureInfoAgent, and other tools, the 3D building process needs to be updated so that the `iri` of a building/feature is included within the RDB and any subsequently generated data files.

This may require a discussion between assignees on how best to implement this.

**Comment by sm453** [comment]
What I had in mind is the following:

When uploading buildings into PostGIS using the stack data uploader, you include into the json config file a node like this:
```json
"otherOptions": {
    "-sql": [
        "SELECT CONCAT('https://www.theworldavatar.com/buildings/building-',\"gml_id\") as iri, * FROM \"buildings\""
    ]
}
```
This adds an `iri` column to the PostGIS table, with IRIs of individuals generated at time of upload based on their `gml_id`. This will make it work out of the box with the DTVF visualisation, including the FeatureInfoAgent.

If we then have abstract building instances that we want to link to those individuals in PostGIS, we should do so using object properties as usual, e.g. with triples such as:
`<abstract building instance IRI> hasLoD2Model https://www.theworldavatar.com/buildings/building-<gml_id>`

**Comment by gpeb2** [comment]
You definitely don't need to duplicate the 3D building data. The data from any CityGML, or similar, files should be stored in Postgres using the 3DcityDB extension. Any extra data relating to those building can be stored in the triple store.
Seb's suggestion is probably the way to go in the near future although that exact setting only works for 2D data at the moment.
We should probably have a discussion about this before proceeding further.

**Comment by mdhillman** [comment]
+1 for setting up a discussion on this (can @yjytt59 arrange this?). What we do will most likely become the default for the majority of our building work, so we need to think it through carefully.

**Comment by sm453** [comment]
It does seem like there is a need for a discussion. I believe a key point is that entities instantiated in PostGIS are still entities like any other in the KG and as such must have an IRI. Any statement (in a triple store) that refers to any such entity must do so by IRI (and not by any other pseudo-identifier like `gml_id`, `InChI`, etc.).

**Comment by yjytt59** [comment]
> What I had in mind is the following:
> 
> When uploading buildings into PostGIS using the stack data uploader, you include into the json config file a node like this:
> 
> ```json
> "otherOptions": {
>     "-sql": [
>         "SELECT CONCAT('https://www.theworldavatar.com/buildings/building-',\"gml_id\") as iri, * FROM \"buildings\""
>     ]
> }
> ```
> 
> This adds an `iri` column to the PostGIS table, with IRIs of individuals generated at time of upload based on their `gml_id`. This will make it work out of the box with the DTVF visualisation, including the FeatureInfoAgent.
> 
> If we then have abstract building instances that we want to link to those individuals in PostGIS, we should do so using object properties as usual, e.g. with triples such as: `<abstract building instance IRI> hasLoD2Model https://www.theworldavatar.com/buildings/building-<gml_id>`

This is a good idea, if stack can generate IRI to store in postgresql, it should be easier for linking of postgresql and blazegraph for more applications. Just a question, if this IRI doesn't exist in blazegraph, have any issues?
I will go to set a disscussion about it.

**Comment by sm453** [comment]
> This is a good idea, if stack can generate IRI to store in postgresql, it should be easier for linking of postgresql and blazegraph for more applications. Just a question, if this IRI doesn't exist in blazegraph, have any issues?

I don't believe that's a problem.
