### ISSUE TITLE
The RemoteStoreClient::executeFederatedQuery method don't work with endpoints with a password

### ISSUE THREAD

**Issue by gpeb2** [cambridge-cares/TheWorldAvatar#740]
The [`RemoteStoreClient::executeFederatedQuery`](https://github.com/cambridge-cares/TheWorldAvatar/blob/80bca4ab84bea190ee67aa606f4cdb154b4c80cf/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteStoreClient.java#L727) method currently uses the [`FedXFactory::createSparqlFederation`](https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/federated/FedXFactory.html#createSparqlFederation(java.util.List)) method to create a federated repository. This method only accepts endpoint URLs and so doesn't work with endpoints that have authentication enabled.

**Comment by gpeb2** [comment]
It looks like the solution would be to create a [`RepositoryManager`](https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/repository/manager/RepositoryManager.html) and add the required endpoints to it along with the appropriate credentials as required. This `RepositoryManager` can then be used to create a `DefaultRepositoryResolver` which can be passed to a `FedXFactory` to create the federated repository.

**Comment by sm453** [comment]
Is this a duplicate issue? C.f. #551

**Comment by gpeb2** [comment]
Duplicate of #551.
