### ISSUE TITLE
add "visualisationSources" as top level node to stack-data-uploader

### ISSUE THREAD

**Issue by cmclscourtney** [cambridge-cares/TheWorldAvatar#769]
To separate GeoServer layers from a single PostGres table. This would allow for multiple views of the same data and provide a more intuitive way of combining data sets, separating the data from the visualisation configuration. 

The current `"geoServerSettings"` within a dataset could continue to be supported but for future developments including the generation of MapBox configurations (#754) this could be supported here. 

One must take care with the order that the datasets and the visualisation sources are uploaded.

```json
{
   "database": ...
   ...
   "dataSubsets": [...],
   "visualisationSources": [...]
}
```

**Comment by gpeb2** [comment]
Any fix for this should probably fix the following issues #275 and #277 too.
