### ISSUE TITLE
DTVF v3.5.0 : "Enable Clipping Planes" Selection Option Missing

### ISSUE THREAD

**Issue by jlai2021** [cambridge-cares/TheWorldAvatar#791]
While using DTVF v3.5.0, I noticed that the option to "Enable Clipping Planes" is missing from the selection menu. This feature was available and fully functional in the previous version, DTVF v3.4.0.

**Comment by sm453** [comment]
I have already requested this in #744.

**Comment by mdhillman** [comment]
Branch updated, please see PR #744

**Comment by mdhillman** [comment]
Closing as completed (and a duplicate).
