### ISSUE TITLE
loadDefinitionsFromURL resolves before data is loaded

### ISSUE THREAD

**Issue by kok-foong** [cambridge-cares/TheWorldAvatar#862]
After running manager.loadDefinitionsFromURL, the tree seems to be lagging one step behind. The data shown on the map is also always from the previous step.

Snippet of my code:   
```
let plotFunction = (function () {
    this.manager.plotData();
}).bind(this);

this.manager.loadDefinitionsFromURL(dataJsonUrl).then(plotFunction());
```

**Comment by kok-foong** [comment]
After some digging, I suspect this is due to `loadDataGroups(dataJSON)`'s promise being resolved before the data is loaded completely. Might have to write the recursion in a way that returns a resolved promise at each level.

**Comment by mdhillman** [comment]
I've commited by testing setup to branch `fix-issue-862`, details on changes are below but it should be noted that this branch should **NOT** be merged (consider it temporary).

- Added a SpringBoot HTTP agent in the `web/digital-twin-vis-framework/test` directory, can be launched using SpringBoot tools in VS Code.
- Updated `local.js` file of example-mapbox-vis to include 3 aforementioned buttons

**Comment by kok-foong** [comment]
Turns out it's because I did not use the arrow function, i.e. `.then(() => plot())`...
