### ISSUE TITLE
TWA-VF: Add ability to switch to different views.

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#885]
The TWA-VF currently allows the specification of a starting position, this could be expanded to provide the ability to switch between multiple pre-configured positions.

This would help with large/long countries that cannot be easily viewed as a single entity. Perhaps helping @ao559x with the Chilean digital twin.

**Comment by ao559x** [comment]
It would be amazing have a selector in the camera options to chose between different settings files.

**Comment by Ushcode** [comment]
* `<a href="#" onclick="MapboxUtils.resetCamera()">Reset to default</a>` in cameraControls, allow this button to be a drop down with multiple named views
* Update documentation
* Views specified in settings.json
* Css for reset to default button now as drop down

**Comment by ao559x** [comment]
Thank you! :)

**Comment by ao559x** [comment]
I haven´t found really how to write the settings file for different views.

**Comment by qhouyee** [comment]
This issue has been resolved in the latest iteration of the visualisation framework which was merged with #1085
