### ISSUE TITLE
TWA-VF: Change position of side panel tabs

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#909]
Explore possibility of moving side panel tabs to the top of the page to better match more standard components.

**Comment by Ushcode** [comment]
![image](https://github.com/cambridge-cares/TheWorldAvatar/assets/102725207/ea760230-71f2-4a21-b0ff-d089d041f171)

**Comment by Ushcode** [comment]
Played around with this for a while, I think it looks better where it's currently sitting at the bottom of the side panel.

New framework has a top nav bar which will be an improvement.

I think we should leave this as is for now
