### ISSUE TITLE
Feature needed on main branch - Branch 808 add pgrouting type 

### ISSUE THREAD

**Issue by ShinZert** [cambridge-cares/TheWorldAvatar#936]
Pirmasens Fair will be happening on 12 Nov. All agents for Pirmasens will be deployed on a digital ocean machine concurrently on the main branch. 

I am creating an IsochroneAgent which is outlined below
- Uses SPARQL to query for points of interest's locations
- Automates the generation isochrones from the locations 
- Calculate based on different transport mode (Walk, Cycle, Drive)
- Calculate population coverage within isochrone
- Input edge table to select flood_cost_table for calculations
- Planned to be used for two use cases -  Pirmasens 15 minute smart city and King's Lynn Flood Router. 

Pre-requisite:
IsochroneAgent will be needing pgrouting features from branch 808.  Currently branch 808 features satisfy the development of IsochroneAgent, no additional features required at the moment.

Timeline: 
Planned 4 weeks time to develop IsochroneAgent. 

The suggestion is to merge 808 features to main in 3-4 weeks, so that there will be sufficient time to troubleshoot and test in case anything (stack-manager or any other agents) breaks on main branch. 

Do let me know your comments on this and if there is already a timeline planned out on merging 808 branch into main. Thank you.

**Comment by sm453** [comment]
Small correction, just for the record: We aim to deploy everything on a physical server in PS.
