### ISSUE TITLE
TimeSeriesClient: methods to initialise new TimeSeries should return created objects.

### ISSUE THREAD

**Issue by mdhillman** [cambridge-cares/TheWorldAvatar#948]
The methods to initialise new time series should ideally return the created TimeSeries<?> instances.

I'm working on generating some sample time series solely for testing, and at the moment I have to initialise the time series in the KG, then go back to the KG again to get them before I can pump in some data.

**Comment by kok-foong** [comment]
Can you elaborate? The initTimeSeries methods only initialise the necessary tables/markup and they don't add any data.

**Comment by mdhillman** [comment]
It would be quite useful it if could either return an unpopulated TimeSeries instance (containing the IRI of the newly generated timeseries) or just the new timeseries IRI.

**Comment by mdhillman** [comment]
Have discussed with @kok-foong, everything is currently handled via the data (dependent column) IRIs. There should be no need to retrieve the IRI of the time series itself.
