### ISSUE TITLE
Data uploader: Allow schema to be specified for each data subset

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#949]
It would be useful if one could explicitly specify the database schema that a dataset should be uploaded to in an input config `json` file, e.g.:
```json
        {
            "type": "...",
            "skip": false,
            "schema": "public",
            "subdirectory": "...",
            ...
        }
```

This would also make the upload process more robust against (accidental or intentional) changes of the default schema in the database.

**Comment by gpeb2** [comment]
linked with #411
